---

  - name: run ssh-agent container
    command: "docker run -d --name=ssh-agent jokius/ssh-agent:latest"

  - name: add ssh keys
    command: "docker run --rm --volumes-from=ssh-agent -v {{ansible_env.HOME}}/.ssh:/ssh jokius/ssh-agent:latest ssh-add /ssh/id_rsa"

  - command: "docker run --rm --volumes-from=ssh-agent -v {{ansible_env.HOME}}/.ssh:/ssh jokius/ssh-agent:latest ssh-add -L"

  - name: add known_hosts
    command: "docker run --rm --volumes-from=ssh-agent -v {{ansible_env.HOME}}/.ssh:/ssh jokius/ssh-agent:latest cp /ssh/known_hosts /root/.ssh/known_hosts"
