---

  - fail: msg='Project name not set'
    when: project_name == ''

  - set_fact: "project_dir={{job_directory}}/{{project_name}}"
    when: job == 'yes' or personal_directory is undefined or personal_directory == ''

  - set_fact: "project_dir={{personal_directory}}/{{project_name}}"
    when: job != 'yes' and personal_directory is defined and personal_directory != ''

  - name: create directory
    file: "path={{project_dir}} state=directory"
